### ISSUE TITLE
Implement work directory structure for spatial runs

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#114] opened 2023-07-18 01:30 UTC

**Comment by ccarouge** [comment] 2023-07-18 01:36
We will be running the spatial runs using payu so we may not need to create the whole structure and rely on payu to create most of it.

**Comment by SeanBryan51** [comment] 2023-08-09 07:21
Closing as duplicate of https://github.com/CABLE-LSM/benchcab/issues/5

**Closed by SeanBryan51** 2023-08-09 07:21 UTC
