### ISSUE TITLE
Define tasks for spatial runs

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#115] opened 2023-07-18 01:31 UTC

**Comment by ccarouge** [comment] 2023-07-18 01:38
We need to come up with a name pattern for these tasks. We may want to keep the "R#_S#" convention so it is similar to the flux site convention.

**Comment by SeanBryan51** [comment] 2023-08-09 07:11
Closing as duplicate of #5

**Closed by SeanBryan51** 2023-08-09 07:11 UTC
